// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: create.proto

package week2demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Create_AddGoods_FullMethodName     = "/create.create/AddGoods"
	Create_UpdateGoods_FullMethodName  = "/create.create/UpdateGoods"
	Create_DelGoods_FullMethodName     = "/create.create/DelGoods"
	Create_GetGoodsById_FullMethodName = "/create.create/GetGoodsById"
	Create_SearchGoods_FullMethodName  = "/create.create/SearchGoods"
)

// CreateClient is the client API for Create service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateClient interface {
	// -----------------------goods-----------------------
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error)
	UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error)
	DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error)
	GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error)
	SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error)
}

type createClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateClient(cc grpc.ClientConnInterface) CreateClient {
	return &createClient{cc}
}

func (c *createClient) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodsResp)
	err := c.cc.Invoke(ctx, Create_AddGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createClient) UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGoodsResp)
	err := c.cc.Invoke(ctx, Create_UpdateGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createClient) DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelGoodsResp)
	err := c.cc.Invoke(ctx, Create_DelGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createClient) GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoodsByIdResp)
	err := c.cc.Invoke(ctx, Create_GetGoodsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createClient) SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGoodsResp)
	err := c.cc.Invoke(ctx, Create_SearchGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateServer is the server API for Create service.
// All implementations must embed UnimplementedCreateServer
// for forward compatibility
type CreateServer interface {
	// -----------------------goods-----------------------
	AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error)
	UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error)
	DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error)
	GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error)
	SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error)
	mustEmbedUnimplementedCreateServer()
}

// UnimplementedCreateServer must be embedded to have forward compatible implementations.
type UnimplementedCreateServer struct {
}

func (UnimplementedCreateServer) AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGoods not implemented")
}
func (UnimplementedCreateServer) UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGoods not implemented")
}
func (UnimplementedCreateServer) DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelGoods not implemented")
}
func (UnimplementedCreateServer) GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsById not implemented")
}
func (UnimplementedCreateServer) SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGoods not implemented")
}
func (UnimplementedCreateServer) mustEmbedUnimplementedCreateServer() {}

// UnsafeCreateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateServer will
// result in compilation errors.
type UnsafeCreateServer interface {
	mustEmbedUnimplementedCreateServer()
}

func RegisterCreateServer(s grpc.ServiceRegistrar, srv CreateServer) {
	s.RegisterService(&Create_ServiceDesc, srv)
}

func _Create_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Create_AddGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServer).AddGoods(ctx, req.(*AddGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Create_UpdateGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServer).UpdateGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Create_UpdateGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServer).UpdateGoods(ctx, req.(*UpdateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Create_DelGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServer).DelGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Create_DelGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServer).DelGoods(ctx, req.(*DelGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Create_GetGoodsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServer).GetGoodsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Create_GetGoodsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServer).GetGoodsById(ctx, req.(*GetGoodsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Create_SearchGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServer).SearchGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Create_SearchGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServer).SearchGoods(ctx, req.(*SearchGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Create_ServiceDesc is the grpc.ServiceDesc for Create service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Create_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "create.create",
	HandlerType: (*CreateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGoods",
			Handler:    _Create_AddGoods_Handler,
		},
		{
			MethodName: "UpdateGoods",
			Handler:    _Create_UpdateGoods_Handler,
		},
		{
			MethodName: "DelGoods",
			Handler:    _Create_DelGoods_Handler,
		},
		{
			MethodName: "GetGoodsById",
			Handler:    _Create_GetGoodsById_Handler,
		},
		{
			MethodName: "SearchGoods",
			Handler:    _Create_SearchGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "create.proto",
}
