// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: create.proto

package week2demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------goods--------------------------------
type Goods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        //商品Id
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     //商品名称
	Price  float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` //商品价格
	Stock  int64   `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`  //商品库存
	Typer  string  `protobuf:"bytes,5,opt,name=typer,proto3" json:"typer,omitempty"`   //商品类型
	Strtus string  `protobuf:"bytes,6,opt,name=strtus,proto3" json:"strtus,omitempty"` //商品状态
}

func (x *Goods) Reset() {
	*x = Goods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{0}
}

func (x *Goods) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Goods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goods) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Goods) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Goods) GetTyper() string {
	if x != nil {
		return x.Typer
	}
	return ""
}

func (x *Goods) GetStrtus() string {
	if x != nil {
		return x.Strtus
	}
	return ""
}

type AddGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     //商品名称
	Price  float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` //商品价格
	Stock  int64   `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`  //商品库存
	Typer  string  `protobuf:"bytes,4,opt,name=typer,proto3" json:"typer,omitempty"`   //商品类型
	Strtus string  `protobuf:"bytes,5,opt,name=strtus,proto3" json:"strtus,omitempty"` //商品状态
}

func (x *AddGoodsReq) Reset() {
	*x = AddGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsReq) ProtoMessage() {}

func (x *AddGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsReq.ProtoReflect.Descriptor instead.
func (*AddGoodsReq) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{1}
}

func (x *AddGoodsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddGoodsReq) GetTyper() string {
	if x != nil {
		return x.Typer
	}
	return ""
}

func (x *AddGoodsReq) GetStrtus() string {
	if x != nil {
		return x.Strtus
	}
	return ""
}

type AddGoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGoodsResp) Reset() {
	*x = AddGoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsResp) ProtoMessage() {}

func (x *AddGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsResp.ProtoReflect.Descriptor instead.
func (*AddGoodsResp) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{2}
}

type UpdateGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        //商品Id
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     //商品名称
	Price  float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` //商品价格
	Stock  int64   `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`  //商品库存
	Typer  string  `protobuf:"bytes,5,opt,name=typer,proto3" json:"typer,omitempty"`   //商品类型
	Strtus string  `protobuf:"bytes,6,opt,name=strtus,proto3" json:"strtus,omitempty"` //商品状态
}

func (x *UpdateGoodsReq) Reset() {
	*x = UpdateGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsReq) ProtoMessage() {}

func (x *UpdateGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsReq.ProtoReflect.Descriptor instead.
func (*UpdateGoodsReq) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGoodsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateGoodsReq) GetTyper() string {
	if x != nil {
		return x.Typer
	}
	return ""
}

func (x *UpdateGoodsReq) GetStrtus() string {
	if x != nil {
		return x.Strtus
	}
	return ""
}

type UpdateGoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateGoodsResp) Reset() {
	*x = UpdateGoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsResp) ProtoMessage() {}

func (x *UpdateGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsResp.ProtoReflect.Descriptor instead.
func (*UpdateGoodsResp) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{4}
}

type DelGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *DelGoodsReq) Reset() {
	*x = DelGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodsReq) ProtoMessage() {}

func (x *DelGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodsReq.ProtoReflect.Descriptor instead.
func (*DelGoodsReq) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{5}
}

func (x *DelGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelGoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelGoodsResp) Reset() {
	*x = DelGoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodsResp) ProtoMessage() {}

func (x *DelGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodsResp.ProtoReflect.Descriptor instead.
func (*DelGoodsResp) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{6}
}

type GetGoodsByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *GetGoodsByIdReq) Reset() {
	*x = GetGoodsByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIdReq) ProtoMessage() {}

func (x *GetGoodsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIdReq.ProtoReflect.Descriptor instead.
func (*GetGoodsByIdReq) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{7}
}

func (x *GetGoodsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGoodsByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods *Goods `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"` //goods
}

func (x *GetGoodsByIdResp) Reset() {
	*x = GetGoodsByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIdResp) ProtoMessage() {}

func (x *GetGoodsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIdResp.ProtoReflect.Descriptor instead.
func (*GetGoodsByIdResp) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{8}
}

func (x *GetGoodsByIdResp) GetGoods() *Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

type SearchGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   int64   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`    //page
	Limit  int64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  //limit
	Id     int64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`        //商品Id
	Name   string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`     //商品名称
	Price  float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"` //商品价格
	Stock  int64   `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`  //商品库存
	Typer  string  `protobuf:"bytes,7,opt,name=typer,proto3" json:"typer,omitempty"`   //商品类型
	Strtus string  `protobuf:"bytes,8,opt,name=strtus,proto3" json:"strtus,omitempty"` //商品状态
}

func (x *SearchGoodsReq) Reset() {
	*x = SearchGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsReq) ProtoMessage() {}

func (x *SearchGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsReq.ProtoReflect.Descriptor instead.
func (*SearchGoodsReq) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{9}
}

func (x *SearchGoodsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchGoodsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchGoodsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SearchGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SearchGoodsReq) GetTyper() string {
	if x != nil {
		return x.Typer
	}
	return ""
}

func (x *SearchGoodsReq) GetStrtus() string {
	if x != nil {
		return x.Strtus
	}
	return ""
}

type SearchGoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods []*Goods `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"` //goods
}

func (x *SearchGoodsResp) Reset() {
	*x = SearchGoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_create_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsResp) ProtoMessage() {}

func (x *SearchGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsResp.ProtoReflect.Descriptor instead.
func (*SearchGoodsResp) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{10}
}

func (x *SearchGoodsResp) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

var File_create_proto protoreflect.FileDescriptor

var file_create_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73, 0x22, 0x7b,
	0x0a, 0x0b, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x8e, 0x01, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x1d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0xb8, 0x01, 0x0a, 0x0e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x32, 0xb9, 0x02,
	0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x64,
	0x64, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3e, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x16,
	0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x35, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x77,
	0x65, 0x65, 0x6b, 0x32, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_create_proto_rawDescOnce sync.Once
	file_create_proto_rawDescData = file_create_proto_rawDesc
)

func file_create_proto_rawDescGZIP() []byte {
	file_create_proto_rawDescOnce.Do(func() {
		file_create_proto_rawDescData = protoimpl.X.CompressGZIP(file_create_proto_rawDescData)
	})
	return file_create_proto_rawDescData
}

var file_create_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_create_proto_goTypes = []any{
	(*Goods)(nil),            // 0: create.Goods
	(*AddGoodsReq)(nil),      // 1: create.AddGoodsReq
	(*AddGoodsResp)(nil),     // 2: create.AddGoodsResp
	(*UpdateGoodsReq)(nil),   // 3: create.UpdateGoodsReq
	(*UpdateGoodsResp)(nil),  // 4: create.UpdateGoodsResp
	(*DelGoodsReq)(nil),      // 5: create.DelGoodsReq
	(*DelGoodsResp)(nil),     // 6: create.DelGoodsResp
	(*GetGoodsByIdReq)(nil),  // 7: create.GetGoodsByIdReq
	(*GetGoodsByIdResp)(nil), // 8: create.GetGoodsByIdResp
	(*SearchGoodsReq)(nil),   // 9: create.SearchGoodsReq
	(*SearchGoodsResp)(nil),  // 10: create.SearchGoodsResp
}
var file_create_proto_depIdxs = []int32{
	0,  // 0: create.GetGoodsByIdResp.goods:type_name -> create.Goods
	0,  // 1: create.SearchGoodsResp.goods:type_name -> create.Goods
	1,  // 2: create.create.AddGoods:input_type -> create.AddGoodsReq
	3,  // 3: create.create.UpdateGoods:input_type -> create.UpdateGoodsReq
	5,  // 4: create.create.DelGoods:input_type -> create.DelGoodsReq
	7,  // 5: create.create.GetGoodsById:input_type -> create.GetGoodsByIdReq
	9,  // 6: create.create.SearchGoods:input_type -> create.SearchGoodsReq
	2,  // 7: create.create.AddGoods:output_type -> create.AddGoodsResp
	4,  // 8: create.create.UpdateGoods:output_type -> create.UpdateGoodsResp
	6,  // 9: create.create.DelGoods:output_type -> create.DelGoodsResp
	8,  // 10: create.create.GetGoodsById:output_type -> create.GetGoodsByIdResp
	10, // 11: create.create.SearchGoods:output_type -> create.SearchGoodsResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_create_proto_init() }
func file_create_proto_init() {
	if File_create_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_create_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Goods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddGoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DelGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DelGoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetGoodsByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetGoodsByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SearchGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_create_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SearchGoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_create_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_create_proto_goTypes,
		DependencyIndexes: file_create_proto_depIdxs,
		MessageInfos:      file_create_proto_msgTypes,
	}.Build()
	File_create_proto = out.File
	file_create_proto_rawDesc = nil
	file_create_proto_goTypes = nil
	file_create_proto_depIdxs = nil
}
